<a href="https://colab.research.google.com/github/tecnocrata/artificial-intelligence-course/blob/master/0.1.Fundamentals/1_Numpy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.array ([10,20,24,5,15,50])
a = np.array ([10,4,40,100,6,2,9,5,6])
a

array([ 10,   4,  40, 100,   6,   2,   9,   5,   6])

# Accediendo y recuperando elementos

In [ ]:
# Acceder al elemento en la posicion 3 (indice basado en cero)
a[2]

40

In [ ]:
# Crear un array desde la posicion 3 en adelante
a[3:]


array([100,   6,   2,   9,   5,   6])

In [ ]:
# Crear un array desde la posicion 3 hasta la 7
a[3:7]

array([100,   6,   2,   9])

In [ ]:
# Desde la posicion 1 toma elementos de 3 en 3 hasta el final
a[1::3]

array([4, 6, 5])

# Creando arreglos de manera dinamica

In [ ]:
# Crear un array de 5 elementos de 0s
ceros = np.zeros (5)
ceros

array([0., 0., 0., 0., 0.])

In [ ]:
# Crear una matriz de 1s de 4x5
np.ones ((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Conociendo el tipo del arreglo
type (ceros)

numpy.ndarray

In [ ]:
# Conociendo el tipo de un elemento del arreglo
type (ceros[3])

numpy.float64

In [ ]:
# Crea un arreglo que distribuye los elementos de acuerdo a lo siguiente
# Empieza en 3, termina en 10 y debe tener 9 elementos
np.linspace (3, 10, 9)

array([ 3.   ,  3.875,  4.75 ,  5.625,  6.5  ,  7.375,  8.25 ,  9.125,
       10.   ])

In [ ]:
# Inicializando un arreglo de 2 dimensiones
b = np.array([['x','y','z'], ['a','b','c']])
print (b)
print (type(b))

[['x' 'y' 'z']
 ['a' 'b' 'c']]
<class 'numpy.ndarray'>


In [ ]:
# La cantidad de dimensiones
print (b.ndim)
# El shape del arreglo
print (b.shape)
b

2
(2, 3)


array([['x', 'y', 'z'],
       ['a', 'b', 'c']], dtype='<U1')

In [ ]:
# Crear un array de 25 elementos, con elementos que van de 0-24
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
# Crear un array de elementos de 5-30, no dice cuantos elementos explicitamente, pero son 30-5 = 25 elementos
np.arange(5,30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
# Crear un array de elementos de 5-50, de 3 en 3, (sin incluir el 50)
np.arange(5,50, 3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [ ]:
# Crear un arreglo de 3x5 lleno de 100s
np.full ((3,5), 100)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [ ]:
# Crear un arreglo que en su diagonal tenga estos elementos
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# Operaciones

In [ ]:
# Ordenamiento
c = [12,4,23, 1]
np.sort (c)

array([ 1,  4, 12, 23])

In [ ]:
# Un ordenamiento personalizado
cabeceras = [('nombre', 'S10'), ('edad', int)]
datos = [('Juan', 10), ('Maria', 70), ('Javier', 70), ('Samuel', 15)]
usuarios = np.array (datos, dtype=cabeceras)

np.sort (usuarios, order = 'edad')

array([(b'Juan', 10), (b'Samuel', 15), (b'Javier', 70), (b'Maria', 70)],
      dtype=[('nombre', 'S10'), ('edad', '<i8')])

# Tarea
Crear un arreglo de 3 dimensiones (nombre, edad, pais) y que se pueda ordernar por cualquiera de ellos

In [ ]:
cabeceras = [('nombre', 'S10'), ('edad', int), ('pais','S20')]
datos = [('Juan', 10,'MX'), ('Maria', 70,'CO'), ('Javier', 50, 'PE'), ('Samuel', 15, 'BO')]
usuarios = np.array (datos, dtype=cabeceras)

np.sort (usuarios, order = 'pais')

array([(b'Samuel', 15, b'BO'), (b'Maria', 70, b'CO'),
       (b'Juan', 10, b'MX'), (b'Javier', 50, b'PE')],
      dtype=[('nombre', 'S10'), ('edad', '<i8'), ('pais', 'S20')])